-- Populate products with sample data
INSERT INTO public.products (category_id, name, description, price, image, features, eco, brand, sizes) VALUES
-- Wall Paints
((SELECT id FROM public.categories WHERE slug = 'wall-paints'), 'Интерьерная краска Premium', 'Высококачественная интерьерная краска с матовым финишем. Идеально подходит для стен в жилых помещениях.', 245.00, '/public/lovable-uploads/0cfee039-9423-4008-a9cd-6439832fb35b.png', ARRAY['Матовый финиш', 'Износостойкая', 'Легко наносится', 'Быстро сохнет'], true, 'AFSONA Premium', ARRAY['1л', '2.5л', '5л', '10л']),
((SELECT id FROM public.categories WHERE slug = 'wall-paints'), 'Краска для стен Эко', 'Экологически чистая краска без запаха. Безопасна для детских комнат и спален.', 189.00, '/public/lovable-uploads/71f2c8f2-9a50-40f6-a04a-ed72628711e1.png', ARRAY['Без запаха', 'Экологична', 'Гипоаллергенна', 'Высокая укрывистость'], true, 'AFSONA Eco', ARRAY['1л', '2.5л', '5л']),
((SELECT id FROM public.categories WHERE slug = 'wall-paints'), 'Латексная краска Deluxe', 'Прочная латексная краска с шелковистым блеском. Устойчива к влаге и загрязнениям.', 299.00, '/public/lovable-uploads/91661c6f-f1ee-4df4-8e2d-ccfb828393fc.png', ARRAY['Шелковистый блеск', 'Влагостойкая', 'Моющаяся', 'Долговечная'], false, 'AFSONA Deluxe', ARRAY['2.5л', '5л', '10л']),

-- Ceiling Paints
((SELECT id FROM public.categories WHERE slug = 'ceiling-paints'), 'Потолочная краска Белоснежная', 'Специальная краска для потолков с высокой укрывистостью и матовым финишем.', 210.00, '/public/lovable-uploads/c88946de-deb3-4226-930f-77d2f016ef99.png', ARRAY['Матовый финиш', 'Высокая укрывистость', 'Не капает', 'Белоснежный цвет'], true, 'AFSONA Ceiling', ARRAY['2.5л', '5л', '10л']),
((SELECT id FROM public.categories WHERE slug = 'ceiling-paints'), 'Краска потолочная Премиум', 'Премиальная потолочная краска с улучшенной формулой для идеального покрытия.', 275.00, '/public/lovable-uploads/0cfee039-9423-4008-a9cd-6439832fb35b.png', ARRAY['Улучшенная формула', 'Легкое нанесение', 'Равномерное покрытие', 'Быстрое высыхание'], true, 'AFSONA Premium', ARRAY['1л', '2.5л', '5л', '10л']),

-- Facade Paints
((SELECT id FROM public.categories WHERE slug = 'facade-paints'), 'Фасадная краска Стойкая', 'Атмосферостойкая фасадная краска для наружных работ с защитой от UV-излучения.', 320.00, '/public/lovable-uploads/71f2c8f2-9a50-40f6-a04a-ed72628711e1.png', ARRAY['UV защита', 'Атмосферостойкая', 'Паропроницаемая', 'Долговечная'], false, 'AFSONA Facade', ARRAY['2.5л', '5л', '10л', '20л']),
((SELECT id FROM public.categories WHERE slug = 'facade-paints'), 'Краска фасадная Эко Плюс', 'Экологичная фасадная краска с улучшенными защитными свойствами.', 385.00, '/public/lovable-uploads/91661c6f-f1ee-4df4-8e2d-ccfb828393fc.png', ARRAY['Экологична', 'Самоочищающаяся', 'Высокая адгезия', 'Цветостойкая'], true, 'AFSONA Eco Plus', ARRAY['5л', '10л', '20л']),

-- Primers
((SELECT id FROM public.categories WHERE slug = 'primers'), 'Грунтовка универсальная', 'Универсальная грунтовка глубокого проникновения для всех типов поверхностей.', 165.00, '/public/lovable-uploads/c88946de-deb3-4226-930f-77d2f016ef99.png', ARRAY['Глубокое проникновение', 'Укрепляет основание', 'Быстро сохнет', 'Экономичный расход'], true, 'AFSONA Base', ARRAY['1л', '2.5л', '5л', '10л']),
((SELECT id FROM public.categories WHERE slug = 'primers'), 'Грунт-концентрат Профи', 'Концентрированная грунтовка для профессионального применения.', 195.00, '/public/lovable-uploads/0cfee039-9423-4008-a9cd-6439832fb35b.png', ARRAY['Концентрат 1:5', 'Глубокое проникновение', 'Антисептические добавки', 'Универсальная'], false, 'AFSONA Professional', ARRAY['1л', '2.5л', '5л']),

-- Decorative Coatings
((SELECT id FROM public.categories WHERE slug = 'decorative-coatings'), 'Декоративная штукатурка Барашек', 'Декоративная минеральная штукатурка с фактурой ''барашек'' для интерьера и фасада.', 450.00, '/public/lovable-uploads/71f2c8f2-9a50-40f6-a04a-ed72628711e1.png', ARRAY['Минеральная основа', 'Фактура барашек', 'Паропроницаемая', 'Колеруется'], true, 'AFSONA Decorative', ARRAY['15кг', '25кг']),
((SELECT id FROM public.categories WHERE slug = 'decorative-coatings'), 'Венецианская штукатурка Люкс', 'Элитная венецианская штукатурка для создания роскошных интерьеров.', 680.00, '/public/lovable-uploads/91661c6f-f1ee-4df4-8e2d-ccfb828393fc.png', ARRAY['Мраморный эффект', 'Глянцевый финиш', 'Водостойкая', 'Ручная работа'], false, 'AFSONA Luxury', ARRAY['5кг', '10кг', '20кг']),

-- Tools
((SELECT id FROM public.categories WHERE slug = 'tools'), 'Валик малярный премиум 25см', 'Профессиональный малярный валик с велюровой шубкой для идеального нанесения краски.', 89.00, '/public/lovable-uploads/c88946de-deb3-4226-930f-77d2f016ef99.png', ARRAY['Велюровая шубка', 'Эргономичная ручка', 'Равномерное нанесение', 'Долговечный'], false, 'AFSONA Tools', ARRAY['25см']),
((SELECT id FROM public.categories WHERE slug = 'tools'), 'Кисть плоская 100мм', 'Плоская кисть из натуральной щетины для точных малярных работ.', 125.00, '/public/lovable-uploads/0cfee039-9423-4008-a9cd-6439832fb35b.png', ARRAY['Натуральная щетина', 'Эргономичная ручка', 'Не оставляет разводов', 'Профессиональное качество'], false, 'AFSONA Professional', ARRAY['100мм']),
((SELECT id FROM public.categories WHERE slug = 'tools'), 'Шпатель металлический 20см', 'Металлический шпатель для нанесения и выравнивания шпаклевочных составов.', 156.00, '/public/lovable-uploads/71f2c8f2-9a50-40f6-a04a-ed72628711e1.png', ARRAY['Нержавеющая сталь', 'Удобная ручка', 'Гибкое лезвие', 'Профессиональный инструмент'], false, 'AFSONA Tools', ARRAY['20см']);