// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbdmochmasoylofhasrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZG1vY2htYXNveWxvZmhhc3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjA5MzIsImV4cCI6MjA3NDYzNjkzMn0.E6Cui94_fN8x_aV6JccT2DWLFjPKBbh6K4NAUY3J278";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});